"""update_payments_fields

Revision ID: 308e20945cc5
Revises: c7f58a2a2f58
Create Date: 2026-07-03 23:17:59.831777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308e20945cc5'
down_revision: Union[str, Sequence[str], None] = 'c7f58a2a2f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE payment_method ADD VALUE 'card'")
    op.execute("ALTER TYPE payment_status ADD VALUE 'overdue'")
    op.add_column('payments', sa.Column('transaction_reference', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('receipt_number', sa.String(length=50), nullable=False))
    op.create_unique_constraint('uq_lease_month_year', 'payments', ['lease_id', 'billing_month', 'billing_year'])
    op.create_unique_constraint(None, 'payments', ['receipt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint('uq_lease_month_year', 'payments', type_='unique')
    op.drop_column('payments', 'receipt_number')
    op.drop_column('payments', 'transaction_reference')
    # ### end Alembic commands ###
