"""add tenants table

Revision ID: 3b978acfb634
Revises: e049e16bb2de
Create Date: 2026-06-29 23:53:03.151457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b978acfb634'
down_revision: Union[str, Sequence[str], None] = 'e049e16bb2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permanent_address', sa.String(length=500), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=False),
    sa.Column('id_proof_type', sa.String(length=50), nullable=False),
    sa.Column('id_proof_number', sa.String(length=100), nullable=False),
    sa.Column('move_in_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'vacated', name='tenant_status'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_room_number_per_building', 'rooms', ['building_id', 'room_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_number_per_building', 'rooms', type_='unique')
    op.drop_table('tenants')
    # ### end Alembic commands ###
