"""add_reminder_sent_at_to_payments

Revision ID: 6ae939aca9cc
Revises: 308e20945cc5
Create Date: 2026-07-04 01:07:32.728639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae939aca9cc'
down_revision: Union[str, Sequence[str], None] = '308e20945cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'reminder_sent_at')
    # ### end Alembic commands ###
